name: Compilar APK de Mi Bodega

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Instalar dependencias del sistema y Buildozer
      run: |
        sudo apt-get update
        # Instalamos las librerías oficiales exactas que pide Kivy para compilar
        sudo apt-get install -y zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
        pip3 install --user --upgrade Cython==0.29.33 buildozer

    - name: Compilar APK
      run: |
        export PATH=$PATH:~/.local/bin
        # Dejamos que Buildozer haga su trabajo de forma natural
        buildozer android debug

    - name: Guardar el APK
      uses: actions/upload-artifact@v4
      with:
        name: Mi-Bodega-APK
        path: bin/*.apk